#
# Copyright (c) 2019, NVIDIA CORPORATION.  All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.
#

ARG CUDA_VERSION=10.0
ARG LINUX_VERSION=centos7
ARG CC_VERSION=7
ARG CXX_VERSION=7
ARG PYTHON_VERSION=3.6

FROM gpuci/rapidsai-base:cuda${CUDA_VERSION}-${LINUX_VERSION}-gcc${CC_VERSION}-py${PYTHON_VERSION}

# Install custom packages
RUN yum -y install rpm-build \
        zlib-devel \
        bzip2-devel \
        xz-devel \
        libcurl-devel \
        wget \
        libssl-dev      # VariantWorks `cyvcf2` dependency

# Install htslib
RUN wget https://github.com/samtools/htslib/releases/download/1.9/htslib-1.9.tar.bz2 && tar xvf htslib-1.9.tar.bz2 && cd htslib-1.9 && ./configure && make -j16 install
