#
# Copyright (c) 2019, NVIDIA CORPORATION.  All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.
#

ARG FROM_IMAGE=gpuci/clara-genomics-base
ARG CUDA_VERSION=9.2
ARG LINUX_VERSION=ubuntu16.04
ARG CC_VERSION=5
ARG CXX_VERSION=5
ARG PYTHON_VERSION=3.6

FROM ${FROM_IMAGE}:cuda${CUDA_VERSION}-${LINUX_VERSION}-gcc${CC_VERSION}-py${PYTHON_VERSION}

# Installs cuda-drivers and cuda libraries for conda builds on CPU-only machines

# Required arguments
ARG DRIVER_VER="440"

# Update and add pkgs
RUN apt-get update -q \
    && apt-get -qq install apt-utils -y --no-install-recommends \
      nvidia-headless-${DRIVER_VER} \
      libnvidia-compute-${DRIVER_VER} \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
