BUILD_IMAGE:
  - gpuci/clara-genomics-base-test

CC_VERSION:
  - 5
  - 7

CUDA_VER:
  - 9.0
  - 9.2
  - 10.0
  - 10.1
  - 10.2
  - 11.0
  - 11.1

LINUX_VERSION:
  - ubuntu16.04
  - ubuntu18.04
  - ubuntu20.04
  - centos7
  - centos8

PYTHON_VERSION:
  - 3.5
  - 3.6
  - 3.7

exclude:
  #Cuda/linux excludes
  - CUDA_VER: 9.0
    LINUX_VER: ubuntu18.04
  - CUDA_VER: 9.0
    LINUX_VER: ubuntu20.04
  - CUDA_VER: 9.2
    LINUX_VER: ubuntu20.04
  - CUDA_VER: 10.0
    LINUX_VER: ubuntu20.04
  - CUDA_VER: 10.1
    LINUX_VER: ubuntu20.04
  - CUDA_VER: 10.2
    LINUX_VER: ubuntu20.04
  - CUDA_VER: 9.0
    LINUX_VER: centos8
  - CUDA_VER: 9.2
    LINUX_VER: centos8
  - CUDA_VER: 10.0
    LINUX_VER: centos8
  # CC/Linux excludes
  - LINUX_VER: ubuntu16.04
    CC_VERSION: 7
  - LINUX_VER: ubuntu18.04
    CC_VERSION: 5
  - LINUX_VER: ubuntu20.04
    CC_VERSION: 5
  - LINUX_VER: centos7
    CC_VERSION: 5
  - LINUX_VER: centos8
    CC_VERSION: 5
